import sys, gzip
import pyxb, pyxb.namespace.utility, toplevel   # Bindings generated by PyXB
import logging

logging.basicConfig(level=logging.DEBUG)

# main script
if len(sys.argv) > 1:
    gcfile = sys.argv[1]
else:
    print "Usage: gnuc2csv.py <gnucash_file> <account_guid>"
    exit(1)

# read GnuCash Data
try:
    f = gzip.open(gcfile)
    gcxml = f.read()
except:
    f = open(gcfile)
    gcxml = f.read()

try:
    doc = toplevel.CreateFromDocument(
          gcxml,
          location_base=gcfile)
    #pyxb.RequireValidWhenGenerating(False)
    print doc.toxml().encode('utf-8')
except pyxb.UnrecognizedContentError as e:
    print '*** ERROR validating response:'
    print e.details()
except pyxb.UnrecognizedDOMRootNodeError as e:
    print '*** ERROR matching content:'
    print e.details()
